name: '🧪 Build & Test Plugin'

on:
  push:
    branches: [master]
    paths-ignore: ['**/*.md']
  pull_request:
    branches: [master]
    paths-ignore: ['**/*.md']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore Jellyfin.Plugin.WhisperSubtitles.sln

      - name: Build
        run: dotnet build Jellyfin.Plugin.WhisperSubtitles.sln --configuration Release --no-restore -warnaserror
